# Address and Port to connect to Websocket
address: localhost
port: 25500

# Server ID to manage your multiple servers.
# Use 0 for automatically use server port.
id: 0

# auto will use the platform type as server name
# Recommend to set this when you have specified id
name: "auto"
