package net.eve0415.mc.WebsocketIntegration.Enum

enum class WSIEventState {
  STARTING,
  STOPPING,
  STATUS,
  CHAT,
  ADVANCEMENT,
  SERVERINFO,
  LOG,
  // For Forge Server
  CONSTRUCTING,
  PREINITIALIZATION,
  INITIALIZATION,
  POSTINITIALIZATION,
  LOADCOMPLETE,
  ABOUTTOSTART,
  GAMESTART
}
